version: "3"
services:
  app:
    container_name: job-controller
    restart: always
    build: .
    ports:
      - "5001:5001"
    volumes:
    - /app/secrets/:/app/secrets/
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"