version: "3"
services:
  job:
    container_name: job-controller
    restart: always
    build: ./job_controller
    ports:
      - "5001:5001"
    volumes:
    - /app/secrets/:/app/secrets/
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
  web:
    container_name: web-controller
    restart: always
    build: ./web_controller
    ports:
      - "3000:3000"
    volumes:
    - /app/uploads:/app/uploads
networks:
  default:
    external:
      name: local-net