version: "3"
services:
  job:
    container_name: job-controller
    restart: always
    build: ./job_controller
    image: capstonegroup17/thecut-app:job-controller
    ports:
      - "5001:5001"
    volumes:
    - /app/secrets/:/app/secrets/
  web:
    container_name: web-controller
    restart: always
    build: ./web_controller
    image: capstonegroup17/thecut-app:web-controller
    ports:
      - "3000:3000"
    volumes:
    - /app/uploads:/app/uploads
networks:
  default:
    external:
      name: local-net