#!/bin/bash

# Pull Images from Docker Hub
docker pull capstonegroup17/thecut-app:job-controller
docker pull capstonegroup17/thecut-app:web-controller

# Stop current running containers
docker stop web-controller job-controller

# Prune all containers
docker container prune -f

# Start up job-controller
docker run -d -p 5001:5001 -v /app/secrets/:/app/secrets/ --network=local-net --name job-controller capstonegroup17/thecut-app:job-controller

# Start up web-controller
docker run -d -p 3000:3000 -v /app/uploads/:/app/uploads/ --network=local-net --name web-controller capstonegroup17/thecut-app:web-controller

# List running containers
docker container ls 